DECLARE @Project as nvarchar(250);										
SET @Project = 'MyProj';

DECLARE @baseClient as nvarchar(250);										
SET @baseClient = 'CustomerKS';
DECLARE @newClient as nvarchar(250);										
SET @newClient = 'CustomerKS_2021';


DECLARE @exclude1 as nvarchar(250);	
DECLARE @exclude2 as nvarchar(250);		
DECLARE @exclude3 as nvarchar(250);								
SET @exclude1 = 'CustomerKS_2020';
SET @exclude2 = 'CustomerKS_Previous_Year';
SET @exclude3 = 'CustomerKS_2021';
										
										
WITH DIR AS (										
	SELECT o.PROJECT_ID, o.OBJECT_ID, o.PARENT_ID, o.OBJECT_NAME NAME, CAST('\' AS nvarchar(max)) FOLDER									
		FROM DSSMDOBJINFO o								
		WHERE o.PARENT_ID = '00000000-0000-0000-0000-000000000000'								
		AND o.OBJECT_NAME <> 'Managed Objects'								
	UNION ALL									
	SELECT o.PROJECT_ID, o.OBJECT_ID, o.PARENT_ID, o.OBJECT_NAME NAME, o2.FOLDER + o2.NAME + '\' FOLDER									
		FROM DSSMDOBJINFO o								
		JOIN DIR o2 ON o.PARENT_ID = o2.OBJECT_ID AND o.PROJECT_ID = o2.PROJECT_ID								
		WHERE o.OBJECT_NAME <> 'System Objects'								
)										
,OBJTYPETEXT AS (										
	SELECT 		 1 ID, 'FILTER' TYPENAME 							
	UNION SELECT 2 , 'TEMPLATE'			UNION SELECT 3 , 'REPORT'			UNION SELECT 4 , 'METRIC'			UNION SELECT 6 , 'AUTOSTYLE'
	UNION SELECT 8 , 'FOLDER'			UNION SELECT 10 , 'PROMPT'			UNION SELECT 11 , 'FUNCTION'		UNION SELECT 12 , 'ATTRIBUTE' 	
	UNION SELECT 13 , 'FACT'			UNION SELECT 14 , 'HIERARCHY'		UNION SELECT 15 , 'TABLE'			UNION SELECT 18 , 'SHORTCUT' 	
	UNION SELECT 21 , 'ATTRIBUTE ID'	UNION SELECT 22 , 'SCHEMA'			UNION SELECT 23 , 'CELL FORMAT' 	UNION SELECT 24 , 'WAREHOUSE CATALOG' 				
	UNION SELECT 25 , 'WAREHOUSE CATALOG DEFINITION'						UNION SELECT 26 , 'TABLE COLUMN'	UNION SELECT 28 , 'PROPERTY SETS' 		
	UNION SELECT 34 , 'USERS/GROUPS'	UNION SELECT 39 , 'SEARCH'			UNION SELECT 42 , 'PACKAGE'			UNION SELECT 43 , 'TRANSFORMATION'		
	UNION SELECT 47 , 'CONSOLIDATION'	UNION SELECT 48 , 'DERIVED ELEMENT' UNION SELECT 52 , 'LINK'		UNION SELECT 53 , 'WAREHOUSE TABLE' 						
	UNION SELECT 55 , 'DOCUMENT'		UNION SELECT 56 , 'DRILLMAP'		UNION SELECT 58 , 'SECFILTER'		UNION SELECT 60 , 'ANSWER' 			
	UNION SELECT 61 , 'GRAPH STYLE'		UNION SELECT 71 , 'PALETTE' 							
	--ELSE 'OTHERS'									
	)									
,RIGHTSTEXT AS (									
	SELECT		199 RIGHTS, 'VIEW' ACL
	UNION SELECT 223 , 'MODIFY'		
	UNION SELECT 255 , 'FULLCONTROL'	
	UNION SELECT 268435711 , 'DENIEDALL'			
	 -- CHILD								
	UNION SELECT 536871111 , 'VIEW' 						
	UNION SELECT 536871135 , 'MODIFY' 						
	UNION SELECT 536871167 , 'FULLCONTROL' 						
	UNION SELECT 805306623 , 'DENIEDALL'  	
)


										
SELECT 										
dbo.fn_UniqueidentifierToCharMSTR(o.OBJECT_ID) GUID										
										
									
,'ADD ACE FOR ' + UPPER(ot.TYPENAME) + ' ''' + o.OBJECT_NAME 										
	+ ''' IN FOLDER ''' + REPLACE(d.Folder,@Project + '\','') + ''' GROUP ''' + REPLACE(t.OBJECT_NAME,@baseClient,@newClient) + ''' '
	
	+ 'ACCESSRIGHTS ' 
	+ CASE WHEN EXISTS (SELECT	1 FROM RIGHTSTEXT r1 WHERE r1.RIGHTS = SUM(CASE WHEN s.RIGHTS <= 268435711 THEN s.RIGHTS ELSE NULL END)) 
		THEN MAX(CASE WHEN s.RIGHTS <= 268435711 THEN r.ACL ELSE NULL END) 
	ELSE 'CUSTOM ' 									
	+REPLACE(CASE WHEN MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END) = 255 THEN '' ELSE 'GRANT ' END									
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,0)) % 2 = 1 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,2)) % 2 = 1 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,3)) % 2 = 1 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,4)) % 2 = 1 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,5)) % 2 = 1 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,6)) % 2 = 1 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS <= 255 THEN s.RIGHTS ELSE NULL END)/POWER(2,7)) % 2 = 1 THEN ',EXECUTE' ELSE '' END								
	 ,'GRANT ,','GRANT ')									
										
	+REPLACE(CASE WHEN MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END) IS NOT NULL THEN ' DENY ' ELSE '' END									 										
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,0)) % 2 = 1 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,2)) % 2 = 1 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,3)) % 2 = 1 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,4)) % 2 = 1 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,5)) % 2 = 1 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,6)) % 2 = 1 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 268435457 AND 268435711 THEN s.RIGHTS ELSE NULL END)/POWER(2,7)) % 2 = 1 THEN ',EXECUTE' ELSE '' END								
		,'DENY ,','DENY ')
										
	+ REPLACE((SELECT CASE WHEN b.BITOR = 255 THEN '' ELSE ' DEFAULT ' END										
		+ CASE WHEN FLOOR(b.bitor/POWER(2,0)) % 2 = 0 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,2)) % 2 = 0 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,3)) % 2 = 0 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,4)) % 2 = 0 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,5)) % 2 = 0 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,6)) % 2 = 0 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,7)) % 2 = 0 THEN ',EXECUTE' ELSE '' END								
	FROM (SELECT SUM(DISTINCT(s1.RIGHTS & 0x01)) +									
				SUM(DISTINCT(s1.RIGHTS & 0x02)) +						
				SUM(DISTINCT(s1.RIGHTS & 0x04)) +						
				SUM(DISTINCT(s1.RIGHTS & 0x08)) +						
				SUM(DISTINCT(s1.RIGHTS & 16)) +						
				SUM(DISTINCT(s1.RIGHTS & 32)) +						
				SUM(DISTINCT(s1.RIGHTS & 64)) +						
				SUM(DISTINCT(s1.RIGHTS & 128)) BITOR						
          FROM DSSMDOBJSECU s1										
          WHERE s1.OBJECT_ID = o.OBJECT_ID AND s1.PROJECT_ID = o.PROJECT_ID 										
			AND s1.TRUST_ID = t.OBJECT_ID							
			AND s1.RIGHTS <= 268435711							
          ) b ),'DEFAULT ,','DEFAULT ')  END 									
										
----------------------------------------------------------										
+ CASE WHEN o.object_type <> 8 THEN '' ELSE ' CHILDRENACCESSRIGHTS '  
	+ CASE WHEN EXISTS (SELECT	1 FROM RIGHTSTEXT r1 WHERE r1.RIGHTS = SUM(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 805306623 THEN s.RIGHTS ELSE NULL END)) 
		THEN MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 805306623 THEN r.ACL ELSE NULL END) 
		ELSE 'CUSTOM ' 										
+REPLACE(CASE WHEN MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END) IS NULL THEN '' ELSE 'GRANT ' END										
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,0)) % 2 = 1 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,2)) % 2 = 1 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,3)) % 2 = 1 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,4)) % 2 = 1 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,5)) % 2 = 1 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,6)) % 2 = 1 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 536871167 THEN s.RIGHTS ELSE NULL END)/POWER(2,7)) % 2 = 1 THEN ',EXECUTE' ELSE '' END								
	 ,'GRANT ,','GRANT ')									
										
+REPLACE(CASE WHEN MAX(CASE WHEN s.RIGHTS BETWEEN 536870913 AND 805306623 THEN s.RIGHTS ELSE NULL END) IS NULL THEN '' ELSE ' DENY ' END 										
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,0)) % 2 = 1 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,2)) % 2 = 1 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,3)) % 2 = 1 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,4)) % 2 = 1 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,5)) % 2 = 1 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,6)) % 2 = 1 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(MAX(CASE WHEN s.RIGHTS BETWEEN 805306369 AND 805306623 THEN s.RIGHTS ELSE NULL END)/POWER(2,7)) % 2 = 1 THEN ',EXECUTE' ELSE '' END								
		,'DENY ,','DENY ')
										
+ REPLACE((SELECT CASE WHEN b.BITOR = 255 OR b.BITOR IS NULL THEN '' ELSE ' DEFAULT ' END										
		+ CASE WHEN FLOOR(b.bitor/POWER(2,0)) % 2 = 0 THEN ',BROWSE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,2)) % 2 = 0 THEN ',READ' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,3)) % 2 = 0 THEN ',WRITE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,4)) % 2 = 0 THEN ',DELETE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,5)) % 2 = 0 THEN ',CONTROL' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,6)) % 2 = 0 THEN ',USE' ELSE '' END								
		+ CASE WHEN FLOOR(b.bitor/POWER(2,7)) % 2 = 0 THEN ',EXECUTE' ELSE '' END								
	FROM (SELECT SUM(DISTINCT(s1.RIGHTS & 0x01)) +									
				SUM(DISTINCT(s1.RIGHTS & 0x02)) +						
				SUM(DISTINCT(s1.RIGHTS & 0x04)) +						
				SUM(DISTINCT(s1.RIGHTS & 0x08)) +						
				SUM(DISTINCT(s1.RIGHTS & 16)) +						
				SUM(DISTINCT(s1.RIGHTS & 32)) +						
				SUM(DISTINCT(s1.RIGHTS & 64)) +						
				SUM(DISTINCT(s1.RIGHTS & 128)) BITOR						
          FROM DSSMDOBJSECU s1										
          WHERE s1.OBJECT_ID = o.OBJECT_ID AND s1.PROJECT_ID = o.PROJECT_ID 										
			AND s1.TRUST_ID = t.OBJECT_ID							
			AND s1.RIGHTS BETWEEN 536870913 AND 805306623							
          ) b ),'DEFAULT ,','DEFAULT ')  END  END 	
		  									
  + ' FOR PROJECT ''' + @Project + ''';' AS CMD										
								
										
,ISNULL(STUFF((SELECT '; ' + CAST(s1.RIGHTS AS nVARCHAR(MAX))										
     FROM DSSMDOBJSECU s1  										
		JOIN DSSMDOBJINFO t1 ON s1.TRUST_ID = t1.OBJECT_ID								
     WHERE s1.OBJECT_ID = o.OBJECT_ID AND s1.PROJECT_ID = o.PROJECT_ID 										
		AND t1.OBJECT_ID = t.object_id								
     FOR XML PATH('')),1,1,''),'') OTHERACCESS										
										
FROM DSSMDOBJINFO o  -- MSTR Object										
JOIN DSSMDOBJSECU s  --security mapping										
	ON s.OBJECT_ID = o.OBJECT_ID AND s.PROJECT_ID = o.PROJECT_ID									
JOIN DSSMDOBJINFO t 										
	ON s.TRUST_ID = t.OBJECT_ID									
										
JOIN DIR d ON o.OBJECT_ID = d.OBJECT_ID AND d.PROJECT_ID = o.PROJECT_ID										
LEFT JOIN OBJTYPETEXT ot ON ot.ID = o.OBJECT_TYPE		

JOIN RIGHTSTEXT r	ON r.RIGHTS = s.RIGHTS								
										
WHERE 										
o.PROJECT_ID = (Select p.object_id From DSSMDOBJINFO p Where p.OBJECT_NAME = @Project AND p.OBJECT_TYPE = 32)										
										
AND t.OBJECT_NAME  LIKE '%' + @baseClient + '%'	

AND t.OBJECT_NAME  NOT LIKE '%' + @exclude1 + '%'	
AND t.OBJECT_NAME  NOT LIKE '%' + @exclude2 + '%'	
AND t.OBJECT_NAME  NOT LIKE '%' + @exclude3 + '%'
 --AND t.SUBTYPE = 8704 -- Users only										
										
 --AND o.object_type = 8  -- Folders only										
AND o.OBJECT_TYPE NOT IN (18)  -- No Shortcuts										
AND d.FOLDER NOT LIKE '%\Profiles\%'										
										
										
GROUP BY o.PROJECT_ID, o.OBJECT_ID, o.OBJECT_NAME, o.OBJECT_TYPE, ot.TYPENAME , d.FOLDER ,t.OBJECT_ID ,T.OBJECT_NAME										
